### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by nataliavaz** [victorcfonseca/GrafanaDashboardAWS#1]
Olá Victor.
Os scripts referenciados no crontab ainda serão disponibilizados?

**Comment by victorcfonseca** [comment]
Oi, Natália.. Bom dia.

Vou disponibilizar sim... no mais tardar no FDS.

Abs,
Victor.

________________________________
De: nataliavaz <notifications@github.com>
Enviado: sexta-feira, 17 de abril de 2020 11:09
Para: victorcfonseca/GrafanaDashboardAWS <GrafanaDashboardAWS@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [victorcfonseca/GrafanaDashboardAWS] Scripts (#1)


Olá Victor.
Os scripts referenciados no crontab ainda serão disponibilizados?

**Comment by nataliavaz** [comment]
Obrigada Victor e parabéns pela iniciativa. Já estou adaptando seu template para meus ambientes :)

**Comment by victorcfonseca** [comment]
Show!! Se possível, depois quero ver como ficou.. ou senão vc faz um post e eu olho o artigo :)

Estou com outras ideias de melhorar esse dash.. tá aqui no meu back log e aos poucos vou colocando em PRD e atualizando o projeto no Github.

Um abraço,
Victor.

________________________________
De: nataliavaz <notifications@github.com>
Enviado: sexta-feira, 17 de abril de 2020 13:34
Para: victorcfonseca/GrafanaDashboardAWS <GrafanaDashboardAWS@noreply.github.com>
Cc: victorcfonseca <victorfonseca1988@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [victorcfonseca/GrafanaDashboardAWS] Scripts (#1)


Obrigada Victor e parabéns pela iniciativa. Já estou adaptando seu template para meus ambientes :)

**Comment by nataliavaz** [comment]
Quando concluir te mostro sim. Mas no dash não pretendo alterar quase nada, até então modifiquei o userparameter para monitorar várias contas diferentes.

**Comment by victorcfonseca** [comment]
Natalia, arquivos disponibilizados dentro do diretório /zabbix/scripts. Se algo a mais for necessário, não deixe de postar / abrir issue. :)

Um abraço,
Victor.

**Comment by nataliavaz** [comment]
Victor, terminei a implementação, depois da uma olhada lá
https://github.com/nataliavaz/grafana-zabbix-aws
