### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by nataliavaz** [victorcfonseca/GrafanaDashboardAWS#2]
Olá Victor. Já baixei os scripts do crontab e adaptei pro meu ambiente.
Não encontrei alguns scripts que são keys em alguns itens, você ainda vai disponibilizá-los?
São eles:
aws-net-inter-avail.sh
aws-net-inter-inuse.sh
aws-no-elasticip.sh
aws-ec2-ondemand.sh
aws-redis.sh
aws-deploy-failed.sh
aws-deploy-succeeded.sh

**Comment by victorcfonseca** [comment]
Oi, Natalia.. acabei de disponibilizar. Estão dentro do diretório /zabbix/externalscripts.

Obrigado por pontuar.
